export const APPOINTMENT_ADD_REQUEST = 'APPOINTMENT_ADD_REQUEST'
export const APPOINTMENT_ADD_SUCCESS = 'APPOINTMENT_ADD_SUCCESS'
export const APPOINTMENT_ADD_FAIL = 'APPOINTMENT_ADD_FAIL'

export const APPOINTMENT_FETCH_REQUEST = 'APPOINTMENT_FETCH_REQUEST'
export const APPOINTMENT_FETCH_SUCCESS = 'APPOINTMENT_FETCH_SUCCESS'
export const APPOINTMENT_FETCH_FAIL = 'APPOINTMENT_FETCH_FAIL'