export const NEW_PROP_COUNT_REQUEST = 'NEW_PROP_COUNT_REQUEST'
export const NEW_PROP_COUNT_SUCCESS = 'NEW_PROP_COUNT_SUCCESS'
export const NEW_PROP_COUNT_FAIL = 'NEW_PROP_COUNT_FAIL'
export const NEW_PROP_COUNT_RESET = 'NEW_PROP_COUNT_RESET'

export const GET_APP_COUNT_REQUEST = 'GET_APP_COUNT_REQUEST'
export const GET_APP_COUNT_SUCCESS = 'GET_APP_COUNT_SUCCESS'
export const GET_APP_COUNT_FAIL = 'GET_APP_COUNT_FAIL'
export const GET_APP_COUNT_RESET = 'GET_APP_COUNT_RESET'

export const GET_PROP_COUNT_REQUEST = 'GET_PROP_COUNT_REQUEST'
export const GET_PROP_COUNT_SUCCESS = 'GET_PROP_COUNT_SUCCESS'
export const GET_PROP_COUNT_FAIL = 'GET_PROP_COUNT_FAIL'
export const GET_PROP_COUNT_RESET = 'GET_PROP_COUNT_RESET'

export const GET_APP_PROP_COUNT_REQUEST = 'GET_APP_PROP_COUNT_REQUEST'
export const GET_APP_PROP_COUNT_SUCCESS = 'GET_APP_PROP_COUNT_SUCCESS'
export const GET_APP_PROP_COUNT_FAIL = 'GET_APP_PROP_COUNT_FAIL'
export const GET_APP_PROP_COUNT_RESET = 'GET_APP_PROP_COUNT_RESET'

export const GET_RENTED_PROP_COUNT_REQUEST = 'GET_RENTED_PROP_COUNT_REQUEST'
export const GET_RENTED_PROP_COUNT_SUCCESS = 'GET_RENTED_PROP_COUNT_SUCCESS'
export const GET_RENTED_PROP_COUNT_FAIL = 'GET_RENTED_PROP_COUNT_FAIL'
export const GET_RENTED_PROP_COUNT_RESET = 'GET_RENTED_PROP_COUNT_RESET'

export const GET_BOOK_COUNT_REQUEST = 'GET_BOOK_COUNT_REQUEST'
export const GET_BOOK_COUNT_SUCCESS = 'GET_BOOK_COUNT_SUCCESS'
export const GET_BOOK_COUNT_FAIL = 'GET_BOOK_COUNT_FAIL'
export const GET_BOOK_COUNT_RESET = 'GET_BOOK_COUNT_RESET'

export const GET_OWNER_COUNT_REQUEST = 'GET_OWNER_COUNT_REQUEST'
export const GET_OWNER_COUNT_SUCCESS = 'GET_OWNER_COUNT_SUCCESS'
export const GET_OWNER_COUNT_FAIL = 'GET_OWNER_COUNT_FAIL'
export const GET_OWNER_COUNT_RESET = 'GET_OWNER_COUNT_RESET'

export const GET_VERIFIER_COUNT_REQUEST = 'GET_VERIFIER_COUNT_REQUEST'
export const GET_VERIFIER_COUNT_SUCCESS = 'GET_VERIFIER_COUNT_SUCCESS'
export const GET_VERIFIER_COUNT_FAIL = 'GET_VERIFIER_COUNT_FAIL'
export const GET_VERIFIER_COUNT_RESET = 'GET_VERIFIER_COUNT_RESET'

export const GET_CUSTOMER_COUNT_REQUEST = 'GET_CUSTOMER_COUNT_REQUEST'
export const GET_CUSTOMER_COUNT_SUCCESS = 'GET_CUSTOMER_COUNT_SUCCESS'
export const GET_CUSTOMER_COUNT_FAIL = 'GET_CUSTOMER_COUNT_FAIL'
export const GET_CUSTOMER_COUNT_RESET = 'GET_CUSTOMER_COUNT_RESET'

export const GET_UNVERIFIED_PROP_COUNT_REQUEST = 'GET_UNVERIFIED_PROP_COUNT_REQUEST'
export const GET_UNVERIFIED_PROP_COUNT_SUCCESS = 'GET_UNVERIFIED_PROP_COUNT_SUCCESS'
export const GET_UNVERIFIED_PROP_COUNT_FAIL = 'GET_UNVERIFIED_PROP_COUNT_FAIL'
export const GET_UNVERIFIED_PROP_COUNT_RESET = 'GET_UNVERIFIED_PROP_COUNT_RESET'

export const GET_VERIFIED_PROP_COUNT_REQUEST = 'GET_VERIFIED_PROP_COUNT_REQUEST'
export const GET_VERIFIED_PROP_COUNT_SUCCESS = 'GET_VERIFIED_PROP_COUNT_SUCCESS'
export const GET_VERIFIED_PROP_COUNT_FAIL = 'GET_VERIFIED_PROP_COUNT_FAIL'
export const GET_VERIFIED_PROP_COUNT_RESET = 'GET_VERIFIED_PROP_COUNT_RESET'

export const GET_APPROVED_PROP_COUNT_REQUEST = 'GET_APPROVED_PROP_COUNT_REQUEST'
export const GET_APPROVED_PROP_COUNT_SUCCESS = 'GET_APPROVED_PROP_COUNT_SUCCESS'
export const GET_APPROVED_PROP_COUNT_FAIL = 'GET_APPROVED_PROP_COUNT_FAIL'
export const GET_APPROVED_PROP_COUNT_RESET = 'GET_APPROVED_PROP_COUNT_RESET'