export const PROP_FETCH_REQUEST = 'PROP_FETCH_REQUEST'
export const PROP_FETCH_SUCCESS = 'PROP_FETCH_SUCCESS'
export const PROP_FETCH_FAIL = 'PROP_FETCH_FAIL'
export const PROP_FETCH_RESET = 'PROP_FETCH_RESET'

export const PROP_ADD_REQUEST = 'PROP_ADD_REQUEST'
export const PROP_ADD_SUCCESS = 'PROP_ADD_SUCCESS'
export const PROP_ADD_FAIL = 'PROP_ADD_FAIL'
export const PROP_ADD_RESET = 'PROP_ADD_RESET'

export const PROP_VERIFY_REQUEST = 'PROP_VERIFY_REQUEST'
export const PROP_VERIFY_SUCCESS = 'PROP_VERIFY_SUCCESS'
export const PROP_VERIFY_FAIL = 'PROP_VERIFY_FAIL'
export const PROP_VERIFY_RESET = 'PROP_VERIFY_RESET'

export const GET_VERIFIED_REQUEST = 'GET_VERIFIED_REQUEST'
export const GET_VERIFIED_SUCCESS = 'GET_VERIFIED_SUCCESS'
export const GET_VERIFIED_FAIL = 'GET_VERIFIED_FAIL'
export const GET_VERIFIED_RESET = 'GET_VERIFIED_RESET'

export const PROP_APPROVE_REQUEST = 'PROP_APPROVE_REQUEST'
export const PROP_APPROVE_SUCCESS = 'PROP_APPROVE_SUCCESS'
export const PROP_APPROVE_FAIL = 'PROP_APPROVE_FAIL'
export const PROP_APPROVE_RESET = 'PROP_APPROVE_RESET'

export const PROP_SEARCH_REQUEST = 'PROP_SEARCH_REQUEST'
export const PROP_SEARCH_SUCCESS = 'PROP_SEARCH_SUCCESS'
export const PROP_SEARCH_FAIL = 'PROP_SEARCH_FAIL'
export const PROP_SEARCH_RESET = 'PROP_SEARCH_RESET'

export const PROP_DELETE_REQUEST = 'PROP_DELETE_REQUEST'
export const PROP_DELETE_SUCCESS = 'PROP_DELETE_SUCCESS'
export const PROP_DELETE_FAIL = 'PROP_DELETE_FAIL'
export const PROP_DELETE_RESET = 'PROP_DELETE_RESET'