export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const OWNER_SIGNUP_REQUEST = 'OWNER_SIGNUP_REQUEST'
export const OWNER_SIGNUP_SUCCESS = 'OWNER_SIGNUP_SUCCESS'
export const OWNER_SIGNUP_FAIL = 'OWNER_SIGNUP_FAIL'

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST'
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL'
export const USER_FETCH_RESET = 'USER_FETCH_RESET'

export const VERIFIER_ADD_REQUEST = 'VERIFIER_ADD_REQUEST'
export const VERIFIER_ADD_SUCCESS = 'VERIFIER_ADD_SUCCESS'
export const VERIFIER_ADD_FAIL = 'VERIFIER_ADD_FAIL'
export const VERIFIER_ADD_RESET = 'VERIFIER_ADD_RESET'

export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'
export const PROFILE_FETCH_RESET = 'PROFILE_FETCH_RESET'

export const BOOKING_FETCH_REQUEST = 'BOOKING_FETCH_REQUEST'
export const BOOKING_FETCH_SUCCESS = 'BOOKING_FETCH_SUCCESS'
export const BOOKING_FETCH_FAIL = 'BOOKING_FETCH_FAIL'
export const BOOKING_FETCH_RESET = 'BOOKING_FETCH_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'
